
modLoader="javafml"
loaderVersion="[43,)"
license="MIT"


[[mods]]
modId="creatingspace"
version = "1.7.1.test_recipe_1"
displayName="Creating Space"
logoFile = "new_logo.png"
credits='''
Source code:
RealAntEngineer
Icicles
Bream

Translation :
RealAntEngineer -> English and French
PopCorn -> Russian and Ukrainian

Textures :
RealAntEngineer
TheTntExpress
Mr.Sodium
Cosmos
'''
authors="Real Ant Engineer"

description='''
test version for the new rocket/automatic version of 1.7.1
'''

[[dependencies.creatingspace]]
modId="create"
mandatory=true
versionRange="[0.5.1.a,)"
ordering="NONE"
side="BOTH"
